-- MySQL Script generated by MySQL Workbench
-- Wed Jul 20 11:41:35 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema data_royal_family
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema data_royal_family
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `data_royal_family` DEFAULT CHARACTER SET latin1 ;
USE `data_royal_family` ;

-- -----------------------------------------------------
-- Table `data_royal_family`.`price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_royal_family`.`price` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `price` DECIMAL(10,0) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `data_royal_family`.`quantity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_royal_family`.`quantity` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `quantity` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `data_royal_family`.`asset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_royal_family`.`asset` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `price_id` INT(11) NOT NULL,
  `quantity_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `price_id`, `quantity_id`),
  INDEX `fk_asset_price` (`price_id` ASC) VISIBLE,
  INDEX `fk_asset_quantity` (`quantity_id` ASC) VISIBLE,
  CONSTRAINT `fk_asset_price`
    FOREIGN KEY (`price_id`)
    REFERENCES `data_royal_family`.`price` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asset_quantity`
    FOREIGN KEY (`quantity_id`)
    REFERENCES `data_royal_family`.`quantity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `data_royal_family`.`profil_royal_family`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_royal_family`.`profil_royal_family` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `avatar` VARCHAR(255) NULL,
  `picture` VARCHAR(255) NULL,
  `status` VARCHAR(80) NOT NULL,
  `firstname` VARCHAR(80) NOT NULL,
  `lastname` VARCHAR(80) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `data_royal_family`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_royal_family`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `data_royal_family`.`price`
-- -----------------------------------------------------
START TRANSACTION;
USE `data_royal_family`;
INSERT INTO `data_royal_family`.`price` (`id`, `price`) VALUES (DEFAULT, 120000);
INSERT INTO `data_royal_family`.`price` (`id`, `price`) VALUES (DEFAULT, 3200000);
INSERT INTO `data_royal_family`.`price` (`id`, `price`) VALUES (DEFAULT, 8600);
INSERT INTO `data_royal_family`.`price` (`id`, `price`) VALUES (DEFAULT, 15600);
INSERT INTO `data_royal_family`.`price` (`id`, `price`) VALUES (DEFAULT, 750);
INSERT INTO `data_royal_family`.`price` (`id`, `price`) VALUES (DEFAULT, 2650);
INSERT INTO `data_royal_family`.`price` (`id`, `price`) VALUES (DEFAULT, 4200);

COMMIT;


-- -----------------------------------------------------
-- Data for table `data_royal_family`.`quantity`
-- -----------------------------------------------------
START TRANSACTION;
USE `data_royal_family`;
INSERT INTO `data_royal_family`.`quantity` (`id`, `quantity`) VALUES (DEFAULT, 32);
INSERT INTO `data_royal_family`.`quantity` (`id`, `quantity`) VALUES (DEFAULT, 5);
INSERT INTO `data_royal_family`.`quantity` (`id`, `quantity`) VALUES (DEFAULT, 5600);
INSERT INTO `data_royal_family`.`quantity` (`id`, `quantity`) VALUES (DEFAULT, 22);
INSERT INTO `data_royal_family`.`quantity` (`id`, `quantity`) VALUES (DEFAULT, 3120);
INSERT INTO `data_royal_family`.`quantity` (`id`, `quantity`) VALUES (DEFAULT, 2680);
INSERT INTO `data_royal_family`.`quantity` (`id`, `quantity`) VALUES (DEFAULT, 250);

COMMIT;


-- -----------------------------------------------------
-- Data for table `data_royal_family`.`profil_royal_family`
-- -----------------------------------------------------
START TRANSACTION;
USE `data_royal_family`;
INSERT INTO `data_royal_family`.`profil_royal_family` (`id`, `avatar`, `picture`, `status`, `firstname`, `lastname`, `description`) VALUES (DEFAULT, NULL, NULL, 'The King', 'Loris', 'Chastanet', 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.');
INSERT INTO `data_royal_family`.`profil_royal_family` (`id`, `avatar`, `picture`, `status`, `firstname`, `lastname`, `description`) VALUES (DEFAULT, NULL, NULL, 'The Queen', 'Lou', 'Gain', 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.');
INSERT INTO `data_royal_family`.`profil_royal_family` (`id`, `avatar`, `picture`, `status`, `firstname`, `lastname`, `description`) VALUES (DEFAULT, NULL, NULL, 'The Princess', 'Frédérique', 'Demas', 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.');
INSERT INTO `data_royal_family`.`profil_royal_family` (`id`, `avatar`, `picture`, `status`, `firstname`, `lastname`, `description`) VALUES (DEFAULT, NULL, NULL, 'The Aunt', 'Lora', 'Pérrichon', 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.');
INSERT INTO `data_royal_family`.`profil_royal_family` (`id`, `avatar`, `picture`, `status`, `firstname`, `lastname`, `description`) VALUES (DEFAULT, NULL, NULL, 'The Uncle', 'Julien', 'Vigneron', 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.');
INSERT INTO `data_royal_family`.`profil_royal_family` (`id`, `avatar`, `picture`, `status`, `firstname`, `lastname`, `description`) VALUES (DEFAULT, NULL, NULL, 'The Prince', 'Sylvain', 'Leguay', 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.');

COMMIT;

